### ISSUE TITLE
Pytest fails silently if there are non conform cpp-files.

### ISSUE THREAD

**Issue by lukas-ramlab** [pytest-dev/pytest-cpp#163] opened 2024-12-13 12:23 UTC
In a repository there were some executables `test_*` generated, which were normal cpp-executable (with no test-suite), but were in the search tree location of `pytest`.

After installing `pytest-cpp`, the call `pytest` was hanging at `collecting` (see below).
```
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /opt/MaxQ/multirobot-backend/mc-backend
configfile: pytest.ini
testpaths: lib/kinematics, lib/python/mc_backend, ros2_ws/src/mc_backend_utils, ros2_ws/src/geometry_control, ros2_ws/src/robot_service_interface, build
plugins: ament-copyright-0.12.11, ament-pep257-0.12.11, launch-testing-1.0.6, ament-lint-0.12.11, ament-flake8-0.12.11, ament-xmllint-0.12.11, launch-testing-ros-0.19.7, cpp-2.6.0, timeout-2.3.1, cov-3.0.0, colcon-core-0.17.0
collecting 10 items 
```

The issue could easily be fixed, by renaming the specific executable files.

# Expected behavior
I think it's good that pytest fails early due to this (at collection already). But it would be very useful to know which file is responsible / why the discovery is failing, and not just hanging.

**Comment by nicoddemus** [comment] 2024-12-13 14:08
> I think it's good that pytest fails early due to this (at collection already). But it would be very useful to know which file is responsible / why the discovery is failing, and not just hanging.

The problem is that pytest-cpp *calls* the executables with known flags (like `--list-tests`), expecting them to be test suites. Of course if those `test_*` files are not really test suites, they will execute whatever they are (they might be waiting for user input, launching applications, etc).

I don't see a simple solution to this problem, but I'm open to suggestions.

Closing this for now, feel free to follow up though.

**Closed by nicoddemus** 2024-12-13 14:08 UTC
